# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48902490fa5ba2d4c28f137af9c474a57da878bcd4f99fc3bc6266cf4ab4f41a372d7d3a87eb4571fbaa7c5a64009e72d42b77955994185d9e6ec13774801d7f

test:
  secret_key_base: c20881545d876353436074c586f305ac0f2796df7dc4b7455113400f0c7f848753f927fe9edb0a7d61fe73629bfbc6a0d083f8f2e011b0363af6edbbec4f6b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
